import { TransformationCardData } from "./Hero.types";

export const CARDS: TransformationCardData[] = [
  {
    name: 'Prasanna',
    studentDept: 'ECE Department',
    studentCollege: 'SSM College of Engineering & Technology',
    professionalRole: 'DevOps Engineer',
    professionalCompany: 'Codifi',
    picture: 'https://wfkq0nguanh0273r.public.blob.vercel-storage.com/mentorbridge-pics/prasanna.jpg',
  },
  {
    name: 'Subash Natrayan',
    studentDept: 'ECE Department',
    studentCollege: 'SSM College of Engineering & Technology',
    professionalRole: 'Fullstack Engineer',
    professionalCompany: 'Frigate',
    picture: 'https://wfkq0nguanh0273r.public.blob.vercel-storage.com/mentorbridge-pics/Subash.jpg',
  },
  {
    name: 'Kiruthika',
    studentDept: 'CSE Department',
    studentCollege: 'SSM College of Engineering & Technology',
    professionalRole: 'Frontend Engineer',
    professionalCompany: 'Techjays',
    picture: 'https://wfkq0nguanh0273r.public.blob.vercel-storage.com/mentorbridge-pics/Kiruthika_G.jpeg',
  },
  {
    name: 'Umar Farooq',
    studentDept: 'CSE Department',
    studentCollege: 'SSM College of Engineering & Technology',
    professionalRole: 'Frontend Engineer',
    professionalCompany: 'Sukiran Solutions Pvt Ltd',
    picture: 'https://wfkq0nguanh0273r.public.blob.vercel-storage.com/mentorbridge-pics/umar_farook.png',
  },
  {
    name: 'Jeyaraman',
    studentDept: 'CSE Department',
    studentCollege: 'SSM College of Engineering & Technology',
    professionalRole: 'Frontend Engineer',
    professionalCompany: 'Covai HelloTruck Pvt Ltd',
    picture: 'https://wfkq0nguanh0273r.public.blob.vercel-storage.com/mentorbridge-pics/jeyaraman.jpg',
  },
  {
    name: 'JeyaShree',
    studentDept: 'CSE Department',
    studentCollege: 'SSM College of Engineering & Technology',
    professionalRole: 'Frontend Engineer',
    professionalCompany: 'Klyonix',
    picture: 'https://wfkq0nguanh0273r.public.blob.vercel-storage.com/mentorbridge-pics/Jeyashree.jpg',
  },
  {
    name: 'SivaSankari',
    studentDept: 'ECE Department',
    studentCollege: 'SSM College of Engineering & Technology',
    professionalRole: 'Backend Engineer',
    professionalCompany: 'Codifi',
    picture: 'https://wfkq0nguanh0273r.public.blob.vercel-storage.com/mentorbridge-pics/Sivasankari.jpg',
  },
  {
    name: 'BalaKrishnan',
    studentDept: 'ECE Department',
    studentCollege: 'SSM College of Engineering & Technology',
    professionalRole: 'Frontend Engineer',
    professionalCompany: 'Techjays',
    picture: 'https://wfkq0nguanh0273r.public.blob.vercel-storage.com/mentorbridge-pics/balakrishnan.jpg',
  },
  {
    name: 'Kajalakshmi',
    studentDept: 'CSE Department',
    studentCollege: 'SSM College of Engineering & Technology',
    professionalRole: 'Frontend Engineer',
    professionalCompany: 'Klyonix',
    picture: 'https://wfkq0nguanh0273r.public.blob.vercel-storage.com/mentorbridge-pics/kajalakshmi.jpeg',
  },
  {
    name: 'Meena',
    studentDept: 'CSE Department',
    studentCollege: 'SSM College of Engineering & Technology',
    professionalRole: 'Frontend Engineer',
    professionalCompany: 'Sukiran Solutions Pvt Ltd',
    picture: 'https://wfkq0nguanh0273r.public.blob.vercel-storage.com/mentorbridge-pics/meena.jpg',
  },
]